### ISSUE TITLE
Suggestion: setAnimationLoop for autorender?

### ISSUE THREAD

**Issue by okydk** [hmans/three-elements#18]
Great work Hendrik! 🎉 I'm a big fan already.

Threejs [require](https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content) the use of `setAnimationLoop` for WebXR content, so maybe that could be the default when autorender is enabled?

Would also be nice to add the WebXR button as a component. 😛

**Comment by hmans** [comment]
🙏  Thank you! I'm releasing 0.2 tomorrow, with -- finally -- an official ("official") announcement post. I'm excited!

With regard to `setAnimationLoop`, I will look into it! It shouldn't be a big change, and I'll need to do it either way, since the project I'm working on aims to have a dash of VR support down the road.

**Comment by hmans** [comment]
> Threejs [require](https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content) the use of `setAnimationLoop` for WebXR content, so maybe that could be the default when autorender is enabled?

I don't have a lot of practical experience with using sAL instead of rAF. From the outside, it sounds like I could feasibly use sAL *all* the time, instead of queueing my own rAFs, even if the application does not intend to actually do any XR. Does using sAL have any drawbacks? I did see that in the Three.js source it directly interacts with WebXRManager.

**Comment by okydk** [comment]
Yes, I think sAL is future proof. Simply seems to be an internal wrapper for selecting appropriate render mechanism on different platforms.

Exciting! Looking forward to read it. I'm actually making a little board game with three, and have just swapped in three-elements - works flawlessly with my Vue workflow! [Now I'm only concerned that it's too easy to manipulate](https://twitter.com/okydk/status/1349413759085912064). 😂

**Comment by hmans** [comment]
If you have anything that you're willing to share, I'd be very happy to see it! The most important thing three-elements needs at this point is people building cool stuff with it and opening issues for the things that didn't work (or didn't work as well as they should have). I will also add a section to the website at some point with links to cool things built with the library, but at the moment it would be depressingly empty, and I don't have the time to work on demos right now (since I'm also working on that other project that three-elements was extracted from. I think it's going to be a _good_ demo, but it's not ready yet.)
