### ISSUE TITLE
[core] Support MutationObserver behind a flag

### ISSUE THREAD

**Issue by RangerMauve** [hmans/three-elements#44]
As per #34 we talked about how MutationObserver isn't necessary for the actual games but is a nice to have.

Just wanted to make sure this feature was being tracked. 😁

In [this comment](https://github.com/hmans/three-elements/pull/34#issuecomment-768923170) it was suggested to have an `observe` toggle in `three-game` which would enable this functionality.

**Comment by hmans** [comment]
Also from my side let me voice my commitment to re-enable this in some fashion in a future (ideally the 0.4) release. Things I want to explore:

- making it opt-in by setting an `observe` attribute (or similar) either on `three-game` or individual elements (or element branches.)
- finding out if we can use a single MutationObserver for a full tree (and not just individual elements)
- possibly implementing our own logic that we can configure to not run _every_ frame, but only every _n_ frames.

**Comment by hmans** [comment]
I've done some experimenting (see the _extremely_ WIP Draft PR above).

The good news is that it's possible to just have one MutationObserver observing the entire tree of a `<three-game>` instance (instead of having one MutationObserver instance per element.)

The bad news is that this doesn't seem to have any noticeable impact on the kind of bad performance we've had with MutationObservers enabled.

Still, as a purely opt-in feature, this is okay, and I will continue to work on it.

**Comment by RangerMauve** [comment]
Is there a way to import this version of the library using skypack?

**Comment by RangerMauve** [comment]
Trying to place some models in a scene, and it's a little frustrating to have to edit the source and reload each time. 😅

**Comment by CodyJasonBennett** [comment]
If nothing else, the parcel setup on codesandbox works very well for this (https://js.new).
