### ISSUE TITLE
Suggestion: add demo with lit-element

### ISSUE THREAD

**Issue by daKmoR** [hmans/three-elements#7]
I assume it will be a "just works" 👍

**Comment by hmans** [comment]
I've seen lit-element, but haven't tried it yet. I think it should just work, yes, just like any other component abstraction on top of custom elements. If I find some time, I will prepare a demo; until then, I'd be happy if someone who is more familiar with lit-element finds the time to experiment with it in a codesandbox.

**Comment by hmans** [comment]
I've prepared a (simple) example that combines three-elements with lit-element. I did indeed have to make some more changes in order to make things _nice_, but they're all very sane and actually helped me make my code simpler. Please note that these changes are part of version 0.2.0, which I have not yet published to NPM.

Live demo:
https://three-elements-examples.netlify.app/lit-element

Source code:
https://github.com/hmans/three-elements/blob/main/examples/lit-element.html

I'm closing this issue for now. Thank you!
